# Generated by Django 5.0 on 2023-12-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(default=None, max_length=128, verbose_name='confirm_password'),
            preserve_default=False,
        ),
    ]
