# Generated by Django 5.0 on 2023-12-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_customuser_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(max_length=128, null=True, verbose_name='confirm_password'),
        ),
    ]
