# Generated by Django 5.0 on 2023-12-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_customuser_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(default=123, max_length=128, verbose_name='confirm_password'),
            preserve_default=False,
        ),
    ]
