# Generated by Django 5.0 on 2023-12-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_customuser_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirm_password',
        ),
    ]
